### ISSUE TITLE
Wrong file name for DwarfTherapist is called in startlnp

### ISSUE THREAD

**Issue by nicolas-abril** [Lazy-Newb-Pack/Lazy-Newb-Pack-Linux#58] opened 2018-07-02 13:38 UTC
When setcap is called in startlnp, the path to DwarfTherapist is "LNP/utilities/dwarf_therapist/DwarfTherapist". 
The correct path is "LNP/utilities/dwarf_therapist/dwarftherapist"

**Comment by lethosor** [comment] 2018-07-02 14:24
Duplicate of #57, fixed in 4a337fd4ec3cf11b0bb8ff7e07c00e6f7a25e195

**Closed as completed by lethosor** 2018-07-02 14:24 UTC
Labels: duplicate
