### ISSUE TITLE
File is missing: ironhand16.png

### ISSUE THREAD

**Issue by Ternvein** [Lazy-Newb-Pack/Lazy-Newb-Pack-Linux#18] opened 2015-08-28 18:25 UTC
I'm running ArchLinux x64 and having the above problem. ironhand16.png is obviously there, but it seems like libgraphics.so problem.
Switching to BMP doesn't help.
Updating libpng doesn't help.
Removing ancient libstdc++ doesn't help.

Arch package version of DF runs fine, but it's not LNB.
So it seems like a compatibility problem.

UPD: Switching to other tilesets/graphics doesn't help either. PNGs are still "missing".

UPD2: Replacing libgraphics.so by the "package" version helped. Though I think it's kind of problem.

**Comment by lethosor** [comment] 2015-08-28 18:50
The issue is most likely a compatibility problem between DF and your system's version of libpng. Try updating distro_fixes.sh with the script [here](https://github.com/Lazy-Newb-Pack/Lazy-Newb-Pack-Linux/blob/master/pack/df_linux/distro_fixes.sh).

**Comment by MauroMombelli** [comment] 2015-11-10 22:55
arch linux 64bit, same problem (with different tileset), the new script fix it. Thank you

**Comment by lethosor** [comment] 2015-11-10 23:56
All right, this should be fixed in the next pack release.

**Closed as completed by lethosor** 2015-11-10 23:56 UTC
Labels: distro
